### ISSUE TITLE
CODE-RADE playbook - docker handler failed

### ISSUE THREAD

**Issue by brucellino** [AAROC/CODE-RADE-jenkins-role#2]
One of the docker handlers has failed in the last run : 

```
RUNNING HANDLER [mongrelion.ansible-role-docker : restart \
\ docker]                                                   /
 -----------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [196.21.182.7]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service docker: Failed to restart docker.service: Unit docker.socket failed to load: No such file or directory.\n"}
```

**Comment by mongrelion** [comment]
Hello, @brucellino 
I ran into this issue as well with this role. The problem was in the unit file for systemd for the Docker service which was trying to find the unit file for the unix socket, which wasn't there. I have simplified the way that we start the docker service and now it's back to work.
Perhaps you could try that out.

Also, I would like to hear your opinion on why you switch from

```
foo: blah=this and=theother thing=meh
```

to

```
foo:
  blah: this
  and: theother
  thing: meh
```

Is it a common/known best practice or just a matter of style? I am willing to include this in mainstream if your argument is good enough :)

Thanks!

**Comment by brucellino** [comment]
hi @mongrelion thanks for the comment ! 

I switched from the first style to the second to make it easier for us to see what has changed from commit to commit. Since git deals with changes by default on a line-by-line basis, the second form made changes much clearer, by highlighting options or parameters of modules, instead of entire actions. 

How's that ? Need more arm twisting :)

**Comment by mongrelion** [comment]
@brucellino that actually sounds like a great idea. Mind updating your repo and submitting a PR? :)
